name: Smart Hospital CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile project
        run: |
          mkdir out
          javac -d out $(find src -name "*.java")

      - name: Run program
        run: java -cp out Main
